### ISSUE TITLE
Add project: factory_boy

### ISSUE THREAD

**Issue by tsouvarev** [ml-tooling/best-of-web-python#13]
**Project details:**
- Project Name: factory_boy
- Github URL: https://github.com/FactoryBoy/factory_boy/
- Category: testing
- License: MIT
- Package Managers: @rbarrois

**Additional context:**

factory_boy is a fixtures replacement based on thoughtbot’s factory_bot. As a fixtures replacement tool, it aims to replace static, hard to maintain fixtures with easy-to-use factories for complex objects. Instead of building an exhaustive test setup with every possible combination of corner cases, factory_boy allows you to use objects customized for the current test, while only declaring the test-specific fields.

**Comment by lukasmasuch** [comment]
@tsouvarev Thanks for your contribution!
