### ISSUE TITLE
Add project: NiceGUI

### ISSUE THREAD

**Issue by falkoschindler** [ml-tooling/best-of-web-python#134]
**Project details:**

- Project Name: NiceGUI
- Github URL: https://github.com/zauberzeug/nicegui/
- Category: Web UI
- License: MIT
- Package Managers: pypi:nicegui dockerhub:zauberzeug/nicegui

**Comment by rodja** [comment]
I would rather suggest the Category "Web UI". Its purpose is more similar to Streamlit. Even if its build on FastAPI and hence can do all the things FastAPI can do.

**Comment by falkoschindler** [comment]
@rodja You're absolutely right. I updated my post.

I was misguided by JustPy, which is very similar to NiceGUI and listed as Web Framework. But it should also be better categorized as Web UI.

**Comment by falkoschindler** [comment]
I created PR #179 to finally add NiceGUI to the project list.

**Comment by lukasmasuch** [comment]
https://github.com/ml-tooling/best-of-web-python/pull/179 is merged. Thanks for the contribution 👍
