### ISSUE TITLE
Add project: drf-spectacular

### ISSUE THREAD

**Issue by tsouvarev** [ml-tooling/best-of-web-python#14]
**Project details:**
- Project Name: drf-spectacular
- Github URL: https://github.com/tfranzel/drf-spectacular
- Category:  openapi-utils
- License: BSD 3-Clause "New" or "Revised" License
- Package Managers: @tfranzel

**Additional context:**
Sane and flexible OpenAPI 3.0 schema generation for Django REST framework.

**Comment by lukasmasuch** [comment]
@tsouvarev Thanks for your contribution. The project is added and will appear in the next update.
